name: Test and scan for vulnerablities

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'

    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@gluo-nv'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run prettier
        run: yarn prettier:check

      - name: Run tsc
        run: yarn tsc

      - name: Run build
        run: yarn build:all

      - name: Run test
        run: yarn test

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
        ignore-unfixed: true
        format: 'table'
